# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev-hello-universe',
                'doc_host': 'https://simonwoodhead.github.io',
                'git_url': 'https://github.com/simonwoodhead/nbdev-hello-universe',
                'lib_path': 'nbdev_hello_universe'},
  'syms': {'nbdev_hello_universe.core': {'nbdev_hello_universe.core.foo': ('core.html#foo', 'nbdev_hello_universe/core.py')}}}